version: '4'
services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/products
    restart: always  # Ensures the container restarts if it crashes
    networks:
      - app-network

  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge